"""
AI内容生成服务

负责生成Roguelike游戏内容
支持Mock模式和真实LLM模式
自动Fallback到Mock模式
"""

import os
import random
import time
from typing import Dict, Any, List, Optional

# 导入日志
from logger.logger import logger, log_timing

# 导入LLM Provider工厂
from .provider_factory import ProviderFactory
from .monster_balance import MonsterBalanceConfig
from .prompt_builder import PromptBuilder
from .ai_validator import AIValidator
from .ai_quality_checker import AIQualityChecker

# 导入缓存
from cache.cache_manager import floor_cache, room_cache, monster_cache, weapon_cache


class AIService:
    """
    AI内容生成服务

    支持多种AI Provider：
    - mock: 本地随机生成（默认）
    - agnes: 调用Agnes AI (OpenAI兼容)
    - mimo: 调用小米MiMo API (Anthropic兼容)

    环境变量：
    - AI_PROVIDER: mock / agnes / mimo / auto (优先级最高)
    - LLM_PROVIDER: mock / mimo (向后兼容)
    - AGNES_API_KEY: Agnes API密钥
    - MIMO_API_KEY: MiMo API密钥
    """

    def __init__(self):
        """初始化"""
        # Mock数据
        self.monster_types = ["goblin", "skeleton", "bat", "slime", "spider"]
        self.weapon_types = ["sword", "axe", "bow", "staff", "dagger"]
        self.rarities = ["common", "uncommon", "rare", "epic", "legendary"]

        # 读取配置（AI_PROVIDER优先，兼容旧LLM_PROVIDER）
        self.provider_type = os.getenv(
            "AI_PROVIDER",
            os.getenv("LLM_PROVIDER", "mock")
        ).lower()

        # 初始化LLM Provider
        self.llm_provider = None
        self.prompt_builder = None

        # 初始化验证器
        self.validator = AIValidator()
        self.quality_checker = AIQualityChecker()

        # 通过工厂创建Provider
        if self.provider_type != "mock":
            self.llm_provider = ProviderFactory.create(self.provider_type)
            if self.llm_provider and self.llm_provider.is_available():
                self.prompt_builder = PromptBuilder()
                provider_name = self.llm_provider.get_provider_name()
                logger.info(f"AIService initialized with {provider_name} provider")
                logger.info(f"Provider config: {self.llm_provider.get_config()}")
            else:
                logger.warning(
                    f"AIService: {self.provider_type} not available, will fallback to mock"
                )
        else:
            logger.info("AIService initialized with Mock mode")

    def _get_ai_mode(self) -> str:
        """
        获取当前AI模式的标识字符串

        Returns:
            动态获取的Provider名称或"mock"
        """
        if self.llm_provider:
            return self.llm_provider.get_provider_name()
        return "mock"

    def _is_llm_mode(self) -> bool:
        """
        检查当前是否使用LLM模式

        Returns:
            True表示使用真实AI Provider
        """
        return self.llm_provider is not None

    @log_timing
    async def generate_floor(
        self,
        floor_level: int,
        player_level: int,
        player_stats: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        生成楼层内容

        Args:
            floor_level: 楼层级别
            player_level: 玩家等级
            player_stats: 玩家属性

        Returns:
            楼层数据
        """
        logger.info(f"Generating floor: level={floor_level}, player={player_level}")

        # 检查缓存
        cached = floor_cache.get_floor(floor_level, player_level)
        if cached:
            logger.info(f"Floor cache hit: level={floor_level}")
            cached["ai_mode"] = cached.get("ai_mode", "cached")
            return cached

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_floor_with_llm(floor_level, player_level, player_stats)

                # 验证和质量检查
                result = self.validator.validate_floor_data(result)
                result = self.quality_checker.check_floor_quality(result, player_level)

                result["ai_mode"] = self._get_ai_mode()

                # 缓存结果
                floor_cache.set_floor(floor_level, player_level, result)

                logger.info(f"Floor generated by MiMo: {result.get('room_count', 0)} rooms")
                return result
            except Exception as e:
                logger.warning(f"MiMo generation failed, retrying once: {e}")

                # 重试一次
                try:
                    result = await self._generate_floor_with_llm(floor_level, player_level, player_stats)
                    result = self.validator.validate_floor_data(result)
                    result = self.quality_checker.check_floor_quality(result, player_level)
                    result["ai_mode"] = self._get_ai_mode()

                    # 缓存结果
                    floor_cache.set_floor(floor_level, player_level, result)

                    logger.info(f"Floor generated by MiMo (retry): {result.get('room_count', 0)} rooms")
                    return result
                except Exception as e2:
                    logger.warning(f"MiMo retry failed, fallback to mock: {e2}")

        # Fallback到Mock
        result = self._mock_generate_floor(floor_level, player_level)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"

        # 缓存Mock结果（较短TTL）
        floor_cache.set_floor(floor_level, player_level, result)

        logger.info(f"Floor generated by Mock: {result.get('room_count', 0)} rooms")
        return result

    @log_timing
    async def generate_room_content(
        self,
        room_id: int,
        room_type: str,
        floor_level: int,
        player_level: int
    ) -> Dict[str, Any]:
        """
        生成房间内容

        Args:
            room_id: 房间ID
            room_type: 房间类型
            floor_level: 楼层级别
            player_level: 玩家等级

        Returns:
            房间内容数据
        """
        logger.info(f"Generating room content: id={room_id}, type={room_type}")

        # 检查缓存
        cached = room_cache.get_room_content(room_id, room_type, floor_level, player_level)
        if cached:
            logger.info(f"Room content cache hit: id={room_id}")
            cached["ai_mode"] = cached.get("ai_mode", "cached")
            return cached

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_room_with_llm(room_id, room_type, floor_level, player_level)

                # 验证和质量检查
                result = self.validator.validate_room_content(result, floor_level)
                result = self.quality_checker.check_room_content_quality(result, player_level)

                result["ai_mode"] = self._get_ai_mode()

                # 缓存结果
                room_cache.set_room_content(room_id, room_type, floor_level, player_level, result)

                logger.info(f"Room content generated by MiMo: monsters={len(result.get('monsters', []))}")
                return result
            except Exception as e:
                logger.warning(f"MiMo generation failed, retrying once: {e}")

                # 重试一次
                try:
                    result = await self._generate_room_with_llm(room_id, room_type, floor_level, player_level)
                    result = self.validator.validate_room_content(result, floor_level)
                    result = self.quality_checker.check_room_content_quality(result, player_level)
                    result["ai_mode"] = self._get_ai_mode()

                    # 缓存结果
                    room_cache.set_room_content(room_id, room_type, floor_level, player_level, result)

                    logger.info(f"Room content generated by MiMo (retry): monsters={len(result.get('monsters', []))}")
                    return result
                except Exception as e2:
                    logger.warning(f"MiMo retry failed, fallback to mock: {e2}")

        # Fallback到Mock
        result = self._mock_generate_room_content(room_id, room_type, floor_level, player_level)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"

        # 缓存Mock结果
        room_cache.set_room_content(room_id, room_type, floor_level, player_level, result)

        logger.info(f"Room content generated by Mock: monsters={len(result.get('monsters', []))}")
        return result

    @log_timing
    async def generate_monsters(
        self,
        room_type: str,
        floor_level: int,
        player_level: int,
        monster_count: Optional[int] = None
    ) -> Dict[str, Any]:
        """
        生成怪物配置

        Args:
            room_type: 房间类型
            floor_level: 楼层级别
            player_level: 玩家等级
            monster_count: 怪物数量

        Returns:
            怪物配置数据
        """
        logger.info(f"Generating monsters: room_type={room_type}, floor={floor_level}")

        # 检查缓存
        cached = monster_cache.get_monsters(room_type, floor_level, player_level, monster_count)
        if cached:
            logger.info(f"Monster cache hit: room_type={room_type}")
            cached["ai_mode"] = cached.get("ai_mode", "cached")
            return cached

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_monsters_with_llm(room_type, floor_level, player_level, monster_count)

                # 验证和质量检查
                result = self.validator.validate_monster_data(result)
                result = self.quality_checker.check_monster_quality(result, player_level)

                result["ai_mode"] = self._get_ai_mode()

                # 缓存结果
                monster_cache.set_monsters(room_type, floor_level, player_level, monster_count, result)

                logger.info(f"Monsters generated by MiMo: {result.get('total_count', 0)} monsters")
                return result
            except Exception as e:
                logger.warning(f"MiMo generation failed, retrying once: {e}")

                # 重试一次
                try:
                    result = await self._generate_monsters_with_llm(room_type, floor_level, player_level, monster_count)
                    result = self.validator.validate_monster_data(result)
                    result = self.quality_checker.check_monster_quality(result, player_level)
                    result["ai_mode"] = self._get_ai_mode()

                    # 缓存结果
                    monster_cache.set_monsters(room_type, floor_level, player_level, monster_count, result)

                    logger.info(f"Monsters generated by MiMo (retry): {result.get('total_count', 0)} monsters")
                    return result
                except Exception as e2:
                    logger.warning(f"MiMo retry failed, fallback to mock: {e2}")

        # Fallback到Mock
        result = self._mock_generate_monsters(room_type, floor_level, player_level, monster_count)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"

        # 缓存Mock结果
        monster_cache.set_monsters(room_type, floor_level, player_level, monster_count, result)

        logger.info(f"Monsters generated by Mock: {result.get('total_count', 0)} monsters")
        return result

    @log_timing
    async def generate_weapon(
        self,
        player_level: int,
        rarity: Optional[str] = None,
        weapon_type: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        生成武器配置

        Args:
            player_level: 玩家等级
            rarity: 稀有度
            weapon_type: 武器类型

        Returns:
            武器配置数据
        """
        logger.info(f"Generating weapon: level={player_level}, rarity={rarity}, type={weapon_type}")

        # 检查缓存
        cached = weapon_cache.get_weapon(player_level, rarity, weapon_type)
        if cached:
            logger.info(f"Weapon cache hit: level={player_level}")
            cached["ai_mode"] = cached.get("ai_mode", "cached")
            return cached

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_weapon_with_llm(player_level, rarity, weapon_type)

                # 验证和质量检查
                result = self.validator.validate_weapon_data(result)
                result = self.quality_checker.check_weapon_quality(result, player_level)

                result["ai_mode"] = self._get_ai_mode()

                # 缓存结果
                weapon_cache.set_weapon(player_level, rarity, weapon_type, result)

                logger.info(f"Weapon generated by MiMo: {result.get('weapon', {}).get('name', 'unknown')}")
                return result
            except Exception as e:
                logger.warning(f"MiMo generation failed, retrying once: {e}")

                # 重试一次
                try:
                    result = await self._generate_weapon_with_llm(player_level, rarity, weapon_type)
                    result = self.validator.validate_weapon_data(result)
                    result = self.quality_checker.check_weapon_quality(result, player_level)
                    result["ai_mode"] = self._get_ai_mode()

                    # 缓存结果
                    weapon_cache.set_weapon(player_level, rarity, weapon_type, result)

                    logger.info(f"Weapon generated by MiMo (retry): {result.get('weapon', {}).get('name', 'unknown')}")
                    return result
                except Exception as e2:
                    logger.warning(f"MiMo retry failed, fallback to mock: {e2}")

        # Fallback到Mock
        result = self._mock_generate_weapon(player_level, rarity, weapon_type)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"

        # 缓存Mock结果
        weapon_cache.set_weapon(player_level, rarity, weapon_type, result)

        logger.info(f"Weapon generated by Mock: {result.get('weapon', {}).get('name', 'unknown')}")
        return result

    # ==================== LLM生成方法 ====================

    def _should_use_llm(self) -> bool:
        """判断是否应该使用LLM"""
        return (
            self.llm_provider is not None
            and self.llm_provider is not None
            and self.llm_provider.is_available()
            and self.prompt_builder is not None
        )

    async def _generate_floor_with_llm(
        self,
        floor_level: int,
        player_level: int,
        player_stats: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """使用LLM生成楼层"""
        prompt = self.prompt_builder.build_floor_prompt(floor_level, player_level, player_stats)
        return await self.llm_provider.generate(prompt)

    async def _generate_room_with_llm(
        self,
        room_id: int,
        room_type: str,
        floor_level: int,
        player_level: int
    ) -> Dict[str, Any]:
        """使用LLM生成房间内容"""
        prompt = self.prompt_builder.build_room_content_prompt(room_id, room_type, floor_level, player_level)
        return await self.llm_provider.generate(prompt)

    async def _generate_monsters_with_llm(
        self,
        room_type: str,
        floor_level: int,
        player_level: int,
        monster_count: Optional[int]
    ) -> Dict[str, Any]:
        """使用LLM生成怪物配置"""
        prompt = self.prompt_builder.build_monster_prompt(room_type, floor_level, player_level, monster_count)
        return await self.llm_provider.generate(prompt)

    async def _generate_weapon_with_llm(
        self,
        player_level: int,
        rarity: Optional[str],
        weapon_type: Optional[str]
    ) -> Dict[str, Any]:
        """使用LLM生成武器配置"""
        prompt = self.prompt_builder.build_weapon_prompt(player_level, rarity, weapon_type)
        return await self.llm_provider.generate(prompt)

    # ==================== Mock生成方法 ====================

    def _mock_generate_floor(self, floor_level: int, player_level: int) -> Dict[str, Any]:
        """Mock生成楼层"""
        room_count = random.randint(8, 12)
        rooms = []

        # 起始房间
        rooms.append(self._generate_start_room(0))

        # 中间房间
        for i in range(1, room_count - 1):
            room_type = self._get_random_room_type(floor_level)
            room = self._generate_room(i, room_type, floor_level, player_level)
            rooms.append(room)

        # Boss房间
        rooms.append(self._generate_boss_room(room_count - 1, floor_level, player_level))

        # 建立连接
        self._setup_connections(rooms)

        return {
            "floor": floor_level,
            "player_level": player_level,
            "room_count": room_count,
            "rooms": rooms
        }

    def _mock_generate_room_content(
        self,
        room_id: int,
        room_type: str,
        floor_level: int,
        player_level: int
    ) -> Dict[str, Any]:
        """Mock生成房间内容"""
        difficulty = self._calculate_difficulty(floor_level, room_type)
        monsters = self._generate_monster_config(room_type, floor_level, player_level)
        rewards = self._generate_reward_config(room_type, floor_level)
        chests = self._generate_chest_config(room_type)

        return {
            "room_id": room_id,
            "room_type": room_type,
            "floor_level": floor_level,
            "player_level": player_level,
            "difficulty": difficulty,
            "monsters": monsters,
            "rewards": rewards,
            "chests": chests
        }

    def _mock_generate_monsters(
        self,
        room_type: str,
        floor_level: int,
        player_level: int,
        monster_count: Optional[int]
    ) -> Dict[str, Any]:
        """Mock生成怪物配置"""
        if monster_count is None:
            monster_count = self._get_monster_count(room_type)

        monsters = []
        for _ in range(monster_count):
            monster_type = random.choice(self.monster_types)
            level = max(1, floor_level + random.randint(-1, 1))
            monsters.append({
                "id": monster_type,
                "count": 1,
                "level": level
            })

        return {
            "monsters": monsters,
            "total_count": monster_count
        }

    def _mock_generate_weapon(
        self,
        player_level: int,
        rarity: Optional[str],
        weapon_type: Optional[str]
    ) -> Dict[str, Any]:
        """Mock生成武器配置"""
        if rarity is None:
            rarity = self._get_random_rarity()
        if weapon_type is None:
            weapon_type = random.choice(self.weapon_types)

        base_damage = 10 + player_level * 2
        rarity_multiplier = self._get_rarity_multiplier(rarity)
        damage = int(base_damage * rarity_multiplier)
        crit_rate = 0.05 + (player_level * 0.01)
        special_effect = self._generate_special_effect(rarity)
        weapon_name = self._generate_weapon_name(rarity, weapon_type)

        return {
            "weapon": {
                "id": f"{rarity}_{weapon_type}",
                "name": weapon_name,
                "description": f"A {rarity} {weapon_type}",
                "type": weapon_type,
                "rarity": rarity,
                "damage": damage,
                "crit_rate_bonus": crit_rate,
                "special_effect": special_effect,
                "fire_rate": 0.3,
                "bullet_speed": 400.0,
                "price": int(damage * 10 * rarity_multiplier)
            }
        }

    # ==================== 辅助方法 ====================

    def _generate_start_room(self, room_id: int) -> Dict[str, Any]:
        """生成起始房间"""
        return {
            "id": room_id,
            "type": "start",
            "monsters": [],
            "rewards": [],
            "chests": 0,
            "connections": []
        }

    def _generate_boss_room(
        self,
        room_id: int,
        floor_level: int,
        player_level: int
    ) -> Dict[str, Any]:
        """生成Boss房间"""
        return {
            "id": room_id,
            "type": "boss",
            "monsters": [
                {
                    "id": "boss_goblin_king",
                    "count": 1,
                    "level": floor_level + 1
                }
            ],
            "rewards": {
                "count": random.randint(3, 5),
                "quality": 2.0 + (floor_level - 1) * 0.3
            },
            "chests": 2,
            "connections": []
        }

    def _generate_room(
        self,
        room_id: int,
        room_type: str,
        floor_level: int,
        player_level: int
    ) -> Dict[str, Any]:
        """生成普通房间"""
        return {
            "id": room_id,
            "type": room_type,
            "monsters": self._generate_monster_config(room_type, floor_level, player_level),
            "rewards": self._generate_reward_config(room_type, floor_level),
            "chests": self._generate_chest_config(room_type),
            "connections": []
        }

    def _get_random_room_type(self, floor_level: int) -> str:
        """获取随机房间类型"""
        rand = random.random()
        if floor_level <= 2:
            if rand < 0.6:
                return "combat"
            elif rand < 0.8:
                return "reward"
            elif rand < 0.9:
                return "event"
            else:
                return "treasure"
        else:
            if rand < 0.4:
                return "combat"
            elif rand < 0.6:
                return "reward"
            elif rand < 0.7:
                return "elite"
            elif rand < 0.8:
                return "event"
            elif rand < 0.9:
                return "shop"
            else:
                return "treasure"

    def _generate_monster_config(
        self,
        room_type: str,
        floor_level: int,
        player_level: int
    ) -> List[Dict[str, Any]]:
        """生成怪物配置 - 使用MonsterBalanceConfig确保数值平衡"""
        monsters = []

        # 确定怪物类型（用于平衡配置）
        if room_type == "elite":
            monster_type = "elite"
        elif room_type == "boss":
            monster_type = "boss"
        else:
            monster_type = "normal"

        # 使用平衡配置生成属性
        config = MonsterBalanceConfig.get_config(monster_type, floor_level)

        if room_type == "combat":
            count = random.randint(2, 4)
            monsters.append({
                "id": random.choice(self.monster_types),
                "count": count,
                "health": config["health"],
                "attack": config["attack"],
                "defense": config["defense"],
                "level": max(1, player_level + random.randint(-1, 1))
            })
            if floor_level > 2:
                # 第二只怪物品稍强
                enhanced_config = MonsterBalanceConfig.get_config("elite", floor_level)
                monsters.append({
                    "id": random.choice(self.monster_types),
                    "count": random.randint(1, 2),
                    "health": int(config["health"] * 1.2),
                    "attack": int(config["attack"] * 1.1),
                    "defense": config["defense"],
                    "level": max(1, player_level + 1)
                })
        elif room_type == "elite":
            elite_config = MonsterBalanceConfig.get_config("elite", floor_level)
            monsters.append({
                "id": "elite_goblin",
                "count": random.randint(1, 2),
                "health": elite_config["health"],
                "attack": elite_config["attack"],
                "defense": elite_config["defense"],
                "level": player_level + 1
            })
            # 精英房间还有普通怪辅助
            monsters.append({
                "id": random.choice(self.monster_types),
                "count": random.randint(1, 3),
                "health": config["health"],
                "attack": config["attack"],
                "defense": config["defense"],
                "level": max(1, player_level)
            })
        elif room_type == "treasure":
            if random.random() < 0.5:
                monsters.append({
                    "id": random.choice(self.monster_types),
                    "count": random.randint(1, 2),
                    "health": config["health"],
                    "attack": config["attack"],
                    "defense": config["defense"],
                    "level": player_level
                })
        elif room_type == "event":
            if random.random() < 0.3:
                monsters.append({
                    "id": random.choice(self.monster_types),
                    "count": random.randint(1, 2),
                    "health": config["health"],
                    "attack": config["attack"],
                    "defense": config["defense"],
                    "level": player_level
                })
        return monsters

    def _generate_reward_config(
        self,
        room_type: str,
        floor_level: int
    ) -> Dict[str, Any]:
        """生成奖励配置"""
        quality = 1.0
        strategy = ""
        items = []

        if room_type == "combat":
            quality = 1.0 + (floor_level - 1) * 0.1
            strategy = random.choice(["power_growth", "balanced", "survival"])
        elif room_type == "elite":
            quality = 1.5 + (floor_level - 1) * 0.15
            strategy = "power_growth"
        elif room_type == "boss":
            quality = 2.0 + (floor_level - 1) * 0.2
            strategy = "power_growth"
        elif room_type == "reward":
            quality = 1.2 + (floor_level - 1) * 0.12
            strategy = "balanced"
        elif room_type == "treasure":
            quality = 1.3 + (floor_level - 1) * 0.13
            strategy = "balanced"

        return {
            "count": random.randint(1, 3),
            "quality": quality,
            "strategy": strategy,
            "items": items
        }

    def _generate_chest_config(self, room_type: str) -> int:
        """生成宝箱配置"""
        if room_type == "treasure":
            return random.randint(2, 3)
        elif room_type == "elite":
            return 1
        elif room_type == "boss":
            return 2
        else:
            return 0

    def _calculate_difficulty(self, floor_level: int, room_type: str) -> int:
        """计算难度"""
        base_difficulty = floor_level
        if room_type == "elite":
            base_difficulty += 1
        elif room_type == "boss":
            base_difficulty += 2
        return min(10, base_difficulty)

    def _setup_connections(self, rooms: List[Dict[str, Any]]) -> None:
        """设置房间连接"""
        for i in range(len(rooms) - 1):
            rooms[i]["connections"].append(i + 1)
            rooms[i + 1]["connections"].append(i)

        if len(rooms) > 4:
            branch_count = random.randint(1, 3)
            for _ in range(branch_count):
                from_idx = random.randint(0, len(rooms) - 3)
                to_idx = from_idx + random.randint(2, 3)
                if to_idx < len(rooms):
                    if to_idx not in rooms[from_idx]["connections"]:
                        rooms[from_idx]["connections"].append(to_idx)
                    if from_idx not in rooms[to_idx]["connections"]:
                        rooms[to_idx]["connections"].append(from_idx)

    def _get_monster_count(self, room_type: str) -> int:
        """获取怪物数量"""
        if room_type == "combat":
            return random.randint(2, 4)
        elif room_type == "elite":
            return random.randint(3, 5)
        elif room_type == "boss":
            return 1
        elif room_type == "treasure":
            return random.randint(0, 2)
        else:
            return random.randint(0, 1)

    def _get_random_rarity(self) -> str:
        """获取随机稀有度"""
        rand = random.random()
        if rand < 0.5:
            return "common"
        elif rand < 0.8:
            return "uncommon"
        elif rand < 0.95:
            return "rare"
        elif rand < 0.99:
            return "epic"
        else:
            return "legendary"

    def _get_rarity_multiplier(self, rarity: str) -> float:
        """获取稀有度倍率"""
        multipliers = {
            "common": 1.0,
            "uncommon": 1.3,
            "rare": 1.6,
            "epic": 2.0,
            "legendary": 3.0
        }
        return multipliers.get(rarity, 1.0)

    def _generate_special_effect(self, rarity: str) -> str:
        """生成特殊效果"""
        if rarity == "common":
            return ""
        elif rarity == "uncommon":
            return random.choice([
                "Increased attack speed",
                "Life steal 5%",
                "Critical chance +10%"
            ])
        elif rarity == "rare":
            return random.choice([
                "Fire damage",
                "Ice damage",
                "Lightning damage",
                "Double damage chance 15%"
            ])
        elif rarity == "epic":
            return random.choice([
                "Chain lightning",
                "Explosive attacks",
                "Time slow on hit",
                "Summon ally on kill"
            ])
        else:
            return random.choice([
                "Instant kill chance 5%",
                "Invincibility on critical",
                "Time rewind",
                "Duplicate attacks"
            ])

    def _generate_weapon_name(self, rarity: str, weapon_type: str) -> str:
        """生成武器名称"""
        prefixes = {
            "common": ["Basic", "Simple", "Rusty"],
            "uncommon": ["Fine", "Sharp", "Sturdy"],
            "rare": ["Ancient", "Enchanted", "Mystic"],
            "epic": ["Epic", "Legendary", "Hero's"],
            "legendary": ["Divine", "Godly", "Eternal"]
        }
        prefix = random.choice(prefixes.get(rarity, ["Basic"]))
        return f"{prefix} {weapon_type.capitalize()}"

    # ==================== Phase 11: 事件和对话生成 ====================

    @log_timing
    async def generate_event(
        self,
        room_type: str,
        player_level: int,
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        生成房间事件

        Args:
            room_type: 房间类型
            player_level: 玩家等级
            context: 上下文信息

        Returns:
            事件数据
        """
        logger.info(f"Generating event: room_type={room_type}, player_level={player_level}")

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_event_with_llm(room_type, player_level, context)
                result["ai_mode"] = self._get_ai_mode()
                logger.info(f"Event generated by MiMo: {result.get('title', 'unknown')}")
                return result
            except Exception as e:
                logger.warning(f"MiMo event generation failed, fallback to mock: {e}")

        # Fallback到Mock
        result = self._mock_generate_event(room_type, player_level)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"
        logger.info(f"Event generated by Mock: {result.get('title', 'unknown')}")
        return result

    @log_timing
    async def generate_dialogue(
        self,
        npc_type: str,
        room_environment: str,
        player_state: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        生成NPC对话

        Args:
            npc_type: NPC类型
            room_environment: 房间环境
            player_state: 玩家状态

        Returns:
            对话数据
        """
        logger.info(f"Generating dialogue: npc_type={npc_type}")

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_dialogue_with_llm(npc_type, room_environment, player_state)
                result["ai_mode"] = self._get_ai_mode()
                logger.info(f"Dialogue generated by MiMo")
                return result
            except Exception as e:
                logger.warning(f"MiMo dialogue generation failed, fallback to mock: {e}")

        # Fallback到Mock
        result = self._mock_generate_dialogue(npc_type)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"
        logger.info(f"Dialogue generated by Mock")
        return result

    async def _generate_event_with_llm(
        self,
        room_type: str,
        player_level: int,
        context: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """使用LLM生成事件"""
        if not self.llm_provider or not self.prompt_builder:
            raise Exception("LLM provider not available")

        prompt = self.prompt_builder.build_event_prompt(room_type, player_level, context)
        response = await self.llm_provider.generate(prompt)

        # 解析JSON响应
        import json
        try:
            result = json.loads(response)
            return result
        except json.JSONDecodeError:
            logger.warning(f"Failed to parse LLM response as JSON: {response[:100]}")
            raise Exception("Invalid JSON response")

    async def _generate_dialogue_with_llm(
        self,
        npc_type: str,
        room_environment: str,
        player_state: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """使用LLM生成对话"""
        if not self.llm_provider or not self.prompt_builder:
            raise Exception("LLM provider not available")

        prompt = self.prompt_builder.build_dialogue_prompt(npc_type, room_environment, player_state)
        response = await self.llm_provider.generate(prompt)

        import json
        try:
            result = json.loads(response)
            return result
        except json.JSONDecodeError:
            logger.warning(f"Failed to parse LLM response as JSON: {response[:100]}")
            raise Exception("Invalid JSON response")

    def _mock_generate_event(self, room_type: str, player_level: int) -> Dict[str, Any]:
        """Mock生成事件"""
        events = [
            {
                "title": "神秘宝箱",
                "description": "你发现了一个发光的宝箱，但周围似乎有陷阱。",
                "choices": [
                    {"text": "打开宝箱", "reward": {"gold": 50, "attack": 2}, "risk": {"damage": 20}},
                    {"text": "小心绕过", "reward": {"health": 10}, "risk": {}},
                    {"text": "设置陷阱", "reward": {"attack": 5}, "risk": {"damage": 10}}
                ]
            },
            {
                "title": "流浪商人",
                "description": "一个神秘的商人出现在你面前，他有一件稀有物品。",
                "choices": [
                    {"text": "购买物品 (50金币)", "reward": {"attack": 5}, "risk": {"lose_gold": 50}},
                    {"text": "拒绝交易", "reward": {}, "risk": {}},
                    {"text": "抢劫商人", "reward": {"gold": 100, "attack": 3}, "risk": {"damage": 30}}
                ]
            },
            {
                "title": "古老石碑",
                "description": "你发现了一块刻满符文的石碑，似乎蕴含着力量。",
                "choices": [
                    {"text": "触摸石碑", "reward": {"max_health": 20}, "risk": {"damage": 15}},
                    {"text": "研究符文", "reward": {"attack": 3}, "risk": {}},
                    {"text": "离开", "reward": {}, "risk": {}}
                ]
            },
            {
                "title": "受伤的冒险者",
                "description": "你遇到了一个受伤的冒险者，他请求你的帮助。",
                "choices": [
                    {"text": "帮助他", "reward": {"health": 20, "gold": 30}, "risk": {}},
                    {"text": "索取报酬", "reward": {"gold": 50}, "risk": {}},
                    {"text": "忽略他", "reward": {}, "risk": {}}
                ]
            }
        ]

        return random.choice(events)

    def _mock_generate_dialogue(self, npc_type: str) -> Dict[str, Any]:
        """Mock生成对话"""
        dialogues = {
            "merchant": {
                "dialogue": ["欢迎，旅行者！", "我这里有些好东西，看看吧。"]
            },
            "sage": {
                "dialogue": ["前方的道路充满危险...", "小心那些暗影生物。"]
            },
            "guard": {
                "dialogue": ["站住！你是谁？", "这里不安全，快离开。"]
            },
            "healer": {
                "dialogue": ["你看起来受伤了。", "让我来治疗你。"]
            }
        }

        return dialogues.get(npc_type, {"dialogue": ["...", "你好。"]})

    @log_timing
    async def generate_upgrade(
        self,
        player_level: int,
        player_stats: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        生成升级强化选项

        Args:
            player_level: 玩家等级
            player_stats: 玩家属性

        Returns:
            强化选项数据
        """
        logger.info(f"Generating upgrade options: level={player_level}")

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_upgrade_with_llm(player_level, player_stats)
                result["ai_mode"] = self._get_ai_mode()
                logger.info(f"Upgrade options generated by MiMo")
                return result
            except Exception as e:
                logger.warning(f"MiMo upgrade generation failed, fallback to mock: {e}")

        # Fallback到Mock
        result = self._mock_generate_upgrade(player_level)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"
        logger.info(f"Upgrade options generated by Mock")
        return result

    async def _generate_upgrade_with_llm(
        self,
        player_level: int,
        player_stats: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """使用LLM生成强化选项"""
        if not self.llm_provider or not self.prompt_builder:
            raise Exception("LLM provider not available")

        prompt = self.prompt_builder.build_upgrade_prompt(player_level, player_stats)
        response = await self.llm_provider.generate(prompt)

        import json
        try:
            result = json.loads(response)
            return result
        except json.JSONDecodeError:
            logger.warning(f"Failed to parse LLM response as JSON: {response[:100]}")
            raise Exception("Invalid JSON response")

    def _mock_generate_upgrade(self, player_level: int) -> Dict[str, Any]:
        """Mock生成强化选项"""
        power_multiplier = 1.0 + (player_level - 1) * 0.1

        upgrades = [
            {
                "id": "mock_attack",
                "name": "暗影力量",
                "description": f"攻击力 +{int(10 * power_multiplier)}",
                "type": "stat_boost",
                "rarity": "uncommon",
                "modifiers": {"attack": int(10 * power_multiplier)},
                "percent_modifiers": {}
            },
            {
                "id": "mock_health",
                "name": "生命源泉",
                "description": f"最大生命 +{int(30 * power_multiplier)}",
                "type": "stat_boost",
                "rarity": "uncommon",
                "modifiers": {"max_health": int(30 * power_multiplier)},
                "percent_modifiers": {}
            },
            {
                "id": "mock_speed",
                "name": "疾风步",
                "description": "移动速度 +15%",
                "type": "stat_boost",
                "rarity": "rare",
                "modifiers": {},
                "percent_modifiers": {"move_speed": 0.15}
            },
            {
                "id": "mock_crit",
                "name": "致命一击",
                "description": "暴击率 +8%",
                "type": "stat_boost",
                "rarity": "rare",
                "modifiers": {},
                "percent_modifiers": {"crit_rate": 0.08}
            },
            {
                "id": "mock_defense",
                "name": "钢铁意志",
                "description": f"防御力 +{int(8 * power_multiplier)}",
                "type": "stat_boost",
                "rarity": "uncommon",
                "modifiers": {"defense": int(8 * power_multiplier)},
                "percent_modifiers": {}
            },
            {
                "id": "mock_heal_kill",
                "name": "嗜血本能",
                "description": "击杀回复 8 生命",
                "type": "ability",
                "rarity": "rare",
                "modifiers": {"heal_on_kill": 8},
                "percent_modifiers": {}
            }
        ]

        # 随机选择3个
        random.shuffle(upgrades)
        return {"upgrades": upgrades[:3]}

    # ==================== Phase 13: AI自适应智能系统 ====================

    @log_timing
    async def generate_difficulty(
        self,
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        生成难度调整建议

        Args:
            context: 游戏上下文(玩家行为数据)

        Returns:
            难度调整数据
        """
        logger.info(f"Generating difficulty adjustment")

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_difficulty_with_llm(context)
                result["ai_mode"] = self._get_ai_mode()
                logger.info(f"Difficulty adjustment generated by MiMo")
                return result
            except Exception as e:
                logger.warning(f"MiMo difficulty generation failed, fallback to mock: {e}")

        # Fallback到Mock
        result = self._mock_generate_difficulty(context)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"
        logger.info(f"Difficulty adjustment generated by Mock")
        return result

    async def _generate_difficulty_with_llm(
        self,
        context: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """使用LLM生成难度调整"""
        if not self.llm_provider or not self.prompt_builder:
            raise Exception("LLM provider not available")

        prompt = self.prompt_builder.build_difficulty_prompt(context)
        response = await self.llm_provider.generate(prompt)

        import json
        try:
            result = json.loads(response)
            return result
        except json.JSONDecodeError:
            logger.warning(f"Failed to parse LLM response as JSON: {response[:100]}")
            raise Exception("Invalid JSON response")

    def _mock_generate_difficulty(self, context: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Mock生成难度调整"""
        if not context:
            return {
                "enemy_hp_multiplier": 1.0,
                "enemy_damage_multiplier": 1.0,
                "elite_spawn_rate": 0.1,
                "reward_multiplier": 1.0
            }

        combat_style = context.get("combat_style", "balanced")
        death_rate = context.get("death_rate", 0.0)
        damage_rate = context.get("damage_rate", 0.0)
        no_hit_rate = context.get("no_hit_rate", 0.0)

        difficulty = {
            "enemy_hp_multiplier": 1.0,
            "enemy_damage_multiplier": 1.0,
            "elite_spawn_rate": 0.1,
            "reward_multiplier": 1.0
        }

        # 根据玩家表现调整
        if combat_style == "expert" or no_hit_rate > 0.5:
            difficulty["enemy_hp_multiplier"] = 1.2
            difficulty["enemy_damage_multiplier"] = 1.15
            difficulty["elite_spawn_rate"] = 0.2
            difficulty["reward_multiplier"] = 1.2
        elif combat_style == "struggling" or death_rate > 3.0:
            difficulty["enemy_hp_multiplier"] = 0.8
            difficulty["enemy_damage_multiplier"] = 0.85
            difficulty["elite_spawn_rate"] = 0.05
            difficulty["reward_multiplier"] = 1.3
        elif combat_style == "aggressive" or damage_rate > 5.0:
            difficulty["enemy_hp_multiplier"] = 1.1
            difficulty["enemy_damage_multiplier"] = 1.05
            difficulty["elite_spawn_rate"] = 0.15
            difficulty["reward_multiplier"] = 1.1

        return difficulty

    @log_timing
    async def generate_room_strategy(
        self,
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        生成房间策略建议

        Args:
            context: 游戏上下文

        Returns:
            房间策略数据
        """
        logger.info(f"Generating room strategy")

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_room_strategy_with_llm(context)
                result["ai_mode"] = self._get_ai_mode()
                logger.info(f"Room strategy generated by MiMo")
                return result
            except Exception as e:
                logger.warning(f"MiMo room strategy generation failed, fallback to mock: {e}")

        # Fallback到Mock
        result = self._mock_generate_room_strategy(context)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"
        logger.info(f"Room strategy generated by Mock")
        return result

    async def _generate_room_strategy_with_llm(
        self,
        context: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """使用LLM生成房间策略"""
        if not self.llm_provider or not self.prompt_builder:
            raise Exception("LLM provider not available")

        prompt = self.prompt_builder.build_room_strategy_prompt(context)
        response = await self.llm_provider.generate(prompt)

        import json
        try:
            result = json.loads(response)
            return result
        except json.JSONDecodeError:
            logger.warning(f"Failed to parse LLM response as JSON: {response[:100]}")
            raise Exception("Invalid JSON response")

    def _mock_generate_room_strategy(self, context: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Mock生成房间策略"""
        if not context:
            return {
                "preferred_room_types": ["combat", "reward", "event"],
                "avoid_room_types": [],
                "recommended_difficulty": "normal"
            }

        combat_style = context.get("combat_style", "balanced")
        upgrade_preference = context.get("upgrade_preference", "balanced")
        health_percent = context.get("current_health_percent", 1.0)

        strategy = {
            "preferred_room_types": ["combat", "reward", "event"],
            "avoid_room_types": [],
            "recommended_difficulty": "normal"
        }

        if combat_style == "expert":
            strategy["preferred_room_types"] = ["combat", "elite", "boss"]
            strategy["recommended_difficulty"] = "hard"
        elif combat_style == "struggling":
            strategy["preferred_room_types"] = ["reward", "treasure", "shop"]
            strategy["avoid_room_types"] = ["elite"]
            strategy["recommended_difficulty"] = "easy"
        elif upgrade_preference == "attack":
            strategy["preferred_room_types"] = ["combat", "elite"]
        elif health_percent < 0.3:
            strategy["preferred_room_types"] = ["reward", "shop"]
            strategy["avoid_room_types"] = ["combat", "elite"]

        return strategy

    @log_timing
    async def generate_npc_memory(
        self,
        npc_id: str,
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        生成NPC记忆响应

        Args:
            npc_id: NPC ID
            context: NPC记忆上下文

        Returns:
            NPC对话数据
        """
        logger.info(f"Generating NPC memory response for: {npc_id}")

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_npc_memory_with_llm(npc_id, context)
                result["ai_mode"] = self._get_ai_mode()
                logger.info(f"NPC memory response generated by MiMo")
                return result
            except Exception as e:
                logger.warning(f"MiMo NPC memory generation failed, fallback to mock: {e}")

        # Fallback到Mock
        result = self._mock_generate_npc_memory(npc_id, context)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"
        logger.info(f"NPC memory response generated by Mock")
        return result

    async def _generate_npc_memory_with_llm(
        self,
        npc_id: str,
        context: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """使用LLM生成NPC记忆响应"""
        if not self.llm_provider or not self.prompt_builder:
            raise Exception("LLM provider not available")

        prompt = self.prompt_builder.build_npc_memory_prompt(npc_id, context)
        response = await self.llm_provider.generate(prompt)

        import json
        try:
            result = json.loads(response)
            return result
        except json.JSONDecodeError:
            logger.warning(f"Failed to parse LLM response as JSON: {response[:100]}")
            raise Exception("Invalid JSON response")

    def _mock_generate_npc_memory(self, npc_id: str, context: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Mock生成NPC记忆响应"""
        if not context:
            return {
                "dialogue": ["你好，旅行者。"],
                "interaction_count": 0,
                "relationship": 0.0
            }

        interaction_count = context.get("interaction_count", 0)
        relationship = context.get("relationship", 0.0)

        if interaction_count == 0:
            dialogue = ["陌生人，你需要帮助吗？"]
        elif interaction_count < 3:
            if relationship > 0:
                dialogue = ["又见面了，很高兴再见到你。"]
            else:
                dialogue = ["又是你...有什么事吗？"]
        else:
            if relationship > 0.5:
                dialogue = ["老朋友！我一直期待你的到来。"]
            elif relationship < -0.3:
                dialogue = ["你又来了...我希望你不是来找麻烦的。"]
            else:
                dialogue = ["欢迎回来，旅行者。"]

        return {
            "dialogue": dialogue,
            "interaction_count": interaction_count,
            "relationship": relationship
        }

    @log_timing
    async def generate_context_event(
        self,
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        生成上下文事件

        Args:
            context: 游戏上下文

        Returns:
            事件数据
        """
        logger.info(f"Generating context event")

        # 尝试使用LLM
        if self._should_use_llm():
            try:
                result = await self._generate_context_event_with_llm(context)
                result["ai_mode"] = self._get_ai_mode()
                logger.info(f"Context event generated by MiMo")
                return result
            except Exception as e:
                logger.warning(f"MiMo context event generation failed, fallback to mock: {e}")

        # Fallback到Mock
        result = self._mock_generate_context_event(context)
        result["ai_mode"] = "mock_fallback" if self._is_llm_mode() else "mock"
        logger.info(f"Context event generated by Mock")
        return result

    async def _generate_context_event_with_llm(
        self,
        context: Optional[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """使用LLM生成上下文事件"""
        if not self.llm_provider or not self.prompt_builder:
            raise Exception("LLM provider not available")

        prompt = self.prompt_builder.build_context_event_prompt(context)
        response = await self.llm_provider.generate(prompt)

        import json
        try:
            result = json.loads(response)
            return result
        except json.JSONDecodeError:
            logger.warning(f"Failed to parse LLM response as JSON: {response[:100]}")
            raise Exception("Invalid JSON response")

    def _mock_generate_context_event(self, context: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Mock生成上下文事件"""
        if not context:
            return {
                "title": "神秘事件",
                "description": "你遇到了一个奇怪的情况。",
                "choices": [
                    {"text": "探索", "reward": {"gold": 20}, "risk": {}},
                    {"text": "离开", "reward": {}, "risk": {}}
                ]
            }

        combat_style = context.get("combat_style", "balanced")
        upgrade_preference = context.get("upgrade_preference", "balanced")
        health_percent = context.get("current_health_percent", 1.0)

        if health_percent < 0.3:
            return {
                "title": "紧急治疗站",
                "description": "你发现了一个废弃的治疗站，但似乎有危险。",
                "choices": [
                    {"text": "冒险治疗", "reward": {"health": 50}, "risk": {"damage": 20}},
                    {"text": "小心使用", "reward": {"health": 25}, "risk": {}},
                    {"text": "离开", "reward": {}, "risk": {}}
                ]
            }
        elif combat_style == "expert":
            return {
                "title": "挑战之门",
                "description": "一扇神秘的门出现在你面前，上面刻着挑战的符文。",
                "choices": [
                    {"text": "接受挑战", "reward": {"attack": 10, "gold": 100}, "risk": {"damage": 50}},
                    {"text": "研究符文", "reward": {"attack": 3}, "risk": {}},
                    {"text": "忽略", "reward": {}, "risk": {}}
                ]
            }
        elif upgrade_preference == "attack":
            return {
                "title": "武器大师",
                "description": "一位年迈的武器大师愿意传授你技巧。",
                "choices": [
                    {"text": "学习攻击技巧", "reward": {"attack": 8}, "risk": {}},
                    {"text": "学习防御技巧", "reward": {"defense": 5}, "risk": {}},
                    {"text": "离开", "reward": {}, "risk": {}}
                ]
            }
        else:
            return {
                "title": "神秘宝箱",
                "description": "你发现了一个发光的宝箱。",
                "choices": [
                    {"text": "打开", "reward": {"gold": 50}, "risk": {"damage": 15}},
                    {"text": "检查陷阱", "reward": {"gold": 20}, "risk": {}},
                    {"text": "离开", "reward": {}, "risk": {}}
                ]
            }
